import { type StudioHistoryItem } from "@/types/studio";

export const DUMMY_HISTORY: StudioHistoryItem[] = [
  // try-on: 2 standard, 2 premium
  {
    id: "hist-001",
    sessionId: "session-demo-001",
    createdAt: "2026-02-26T14:30:00Z",
    type: "try-on",
    mode: "standard",
    sourceImageUrl: "/dummy/source-1.svg",
    resultImageUrl: "/dummy/result-1.svg",
    params: {
      sourceImage: "/dummy/source-1.svg",
      referenceImage: "/dummy/ref-1.svg",
    },
    modelUsed: "gemini-2.5-flash-image",
    fallbackUsed: false,
    processingTime: 12000,
  },
  {
    id: "hist-002",
    sessionId: "session-demo-001",
    createdAt: "2026-02-26T11:15:00Z",
    type: "try-on",
    mode: "standard",
    sourceImageUrl: "/dummy/source-2.svg",
    resultImageUrl: "/dummy/result-2.svg",
    params: {
      sourceImage: "/dummy/source-2.svg",
      referenceImage: "/dummy/ref-2.svg",
    },
    modelUsed: "gemini-2.5-flash-image",
    fallbackUsed: false,
    processingTime: 10500,
  },
  {
    id: "hist-003",
    sessionId: "session-demo-001",
    createdAt: "2026-02-25T16:45:00Z",
    type: "try-on",
    mode: "premium",
    sourceImageUrl: "/dummy/source-3.svg",
    resultImageUrl: "/dummy/result-3.svg",
    params: {
      sourceImage: "/dummy/source-3.svg",
      referenceImage: "/dummy/ref-3.svg",
    },
    modelUsed: "gemini-3-pro-image-preview",
    fallbackUsed: false,
    processingTime: 22000,
  },
  {
    id: "hist-004",
    sessionId: "session-demo-001",
    createdAt: "2026-02-25T09:20:00Z",
    type: "try-on",
    mode: "premium",
    sourceImageUrl: "/dummy/source-4.svg",
    resultImageUrl: "/dummy/result-4.svg",
    params: {
      sourceImage: "/dummy/source-4.svg",
      referenceImage: "/dummy/ref-4.svg",
    },
    modelUsed: "gemini-3-pro-image-preview",
    fallbackUsed: true,
    processingTime: 25000,
  },

  // color-swap: 2 standard, 2 premium
  {
    id: "hist-005",
    sessionId: "session-demo-001",
    createdAt: "2026-02-24T13:00:00Z",
    type: "color-swap",
    mode: "standard",
    sourceImageUrl: "/dummy/source-5.svg",
    resultImageUrl: "/dummy/result-5.svg",
    params: {
      sourceImage: "/dummy/source-5.svg",
      targetColor: "#1E3A5F",
      garmentRegion: "top",
    },
    modelUsed: "gemini-2.5-flash-image",
    fallbackUsed: false,
    processingTime: 9500,
  },
  {
    id: "hist-006",
    sessionId: "session-demo-001",
    createdAt: "2026-02-24T10:30:00Z",
    type: "color-swap",
    mode: "standard",
    sourceImageUrl: "/dummy/source-6.svg",
    resultImageUrl: "/dummy/result-6.svg",
    params: { sourceImage: "/dummy/source-6.svg", targetColor: "#C41E3A" },
    modelUsed: "gemini-2.5-flash-image",
    fallbackUsed: false,
    processingTime: 8500,
  },
  {
    id: "hist-007",
    sessionId: "session-demo-001",
    createdAt: "2026-02-23T17:10:00Z",
    type: "color-swap",
    mode: "premium",
    sourceImageUrl: "/dummy/source-7.svg",
    resultImageUrl: "/dummy/result-7.svg",
    params: {
      sourceImage: "/dummy/source-7.svg",
      targetColor: "#F5F5DC",
      garmentRegion: "dress",
    },
    modelUsed: "gemini-3-pro-image-preview",
    fallbackUsed: false,
    processingTime: 18000,
  },
  {
    id: "hist-008",
    sessionId: "session-demo-001",
    createdAt: "2026-02-23T08:50:00Z",
    type: "color-swap",
    mode: "premium",
    sourceImageUrl: "/dummy/source-8.svg",
    resultImageUrl: "/dummy/result-8.svg",
    params: {
      sourceImage: "/dummy/source-8.svg",
      targetColor: "#2E8B57",
      garmentRegion: "bottom",
    },
    modelUsed: "gemini-3-pro-image-preview",
    fallbackUsed: false,
    processingTime: 19500,
  },

  // pose-transfer: 2 standard, 2 premium
  {
    id: "hist-009",
    sessionId: "session-demo-001",
    createdAt: "2026-02-22T15:20:00Z",
    type: "pose-transfer",
    mode: "standard",
    sourceImageUrl: "/dummy/source-9.svg",
    resultImageUrl: "/dummy/result-9.svg",
    params: {
      sourceImage: "/dummy/source-9.svg",
      poseType: "preset",
      presetId: "pose-front",
    },
    modelUsed: "gemini-2.5-flash-image",
    fallbackUsed: false,
    processingTime: 11000,
  },
  {
    id: "hist-010",
    sessionId: "session-demo-001",
    createdAt: "2026-02-22T12:00:00Z",
    type: "pose-transfer",
    mode: "standard",
    sourceImageUrl: "/dummy/source-10.svg",
    resultImageUrl: "/dummy/result-10.svg",
    params: {
      sourceImage: "/dummy/source-10.svg",
      poseType: "preset",
      presetId: "pose-side",
    },
    modelUsed: "gemini-2.5-flash-image",
    fallbackUsed: false,
    processingTime: 10000,
  },
  {
    id: "hist-011",
    sessionId: "session-demo-001",
    createdAt: "2026-02-21T18:40:00Z",
    type: "pose-transfer",
    mode: "premium",
    sourceImageUrl: "/dummy/source-11.svg",
    resultImageUrl: "/dummy/result-11.svg",
    params: {
      sourceImage: "/dummy/source-11.svg",
      poseType: "custom",
      poseReferenceImage: "/dummy/pose-ref-11.svg",
    },
    modelUsed: "gemini-3-pro-image-preview",
    fallbackUsed: true,
    processingTime: 24000,
  },
  {
    id: "hist-012",
    sessionId: "session-demo-001",
    createdAt: "2026-02-21T10:05:00Z",
    type: "pose-transfer",
    mode: "premium",
    sourceImageUrl: "/dummy/source-12.svg",
    resultImageUrl: "/dummy/result-12.svg",
    params: {
      sourceImage: "/dummy/source-12.svg",
      poseType: "preset",
      presetId: "pose-back",
    },
    modelUsed: "gemini-3-pro-image-preview",
    fallbackUsed: false,
    processingTime: 20000,
  },
];
